/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CreditScoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeProfileCount"
      | "calculateScore"
      | "createProfile"
      | "creditProfiles"
      | "deleteProfile"
      | "getActiveProfileCount"
      | "getDecryptedScore"
      | "getEncryptedScore"
      | "getProfile"
      | "getScoreWeights"
      | "hasProfile"
      | "isScoreFinalized"
      | "protocolId"
      | "requestScoreDecryption"
      | "scoreDecryptionCallback"
      | "updateProfile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProfileCreated"
      | "ProfileDeleted"
      | "ProfileUpdated"
      | "ScoreCalculated"
      | "ScoreDecryptionRequested"
      | "ScoreRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeProfileCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "creditProfiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveProfileCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getScoreWeights",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isScoreFinalized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestScoreDecryption",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scoreDecryptionCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeProfileCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveProfileCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getScoreWeights",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isScoreFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestScoreDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "scoreDecryptionCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileDeletedEvent {
  export type InputTuple = [owner: AddressLike];
  export type OutputTuple = [owner: string];
  export interface OutputObject {
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreCalculatedEvent {
  export type InputTuple = [owner: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [owner: string, timestamp: bigint];
  export interface OutputObject {
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreDecryptionRequestedEvent {
  export type InputTuple = [owner: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [owner: string, requestId: bigint];
  export interface OutputObject {
    owner: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreRevealedEvent {
  export type InputTuple = [owner: AddressLike, score: BigNumberish];
  export type OutputTuple = [owner: string, score: bigint];
  export interface OutputObject {
    owner: string;
    score: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreditScore extends BaseContract {
  connect(runner?: ContractRunner | null): CreditScore;
  waitForDeployment(): Promise<this>;

  interface: CreditScoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeProfileCount: TypedContractMethod<[], [bigint], "view">;

  calculateScore: TypedContractMethod<[], [void], "nonpayable">;

  createProfile: TypedContractMethod<
    [
      encryptedIncome: BytesLike,
      incomeProof: BytesLike,
      encryptedRepaymentRate: BytesLike,
      repaymentProof: BytesLike,
      encryptedDebtRatio: BytesLike,
      debtProof: BytesLike,
      encryptedCreditHistory: BytesLike,
      historyProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  creditProfiles: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        encryptedIncome: string;
        encryptedRepaymentRate: string;
        encryptedDebtRatio: string;
        encryptedCreditHistory: string;
        encryptedScore: string;
        timestamp: bigint;
        owner: string;
        isActive: boolean;
        scoreCalculated: boolean;
      }
    ],
    "view"
  >;

  deleteProfile: TypedContractMethod<[], [void], "nonpayable">;

  getActiveProfileCount: TypedContractMethod<[], [bigint], "view">;

  getDecryptedScore: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEncryptedScore: TypedContractMethod<[user: AddressLike], [string], "view">;

  getProfile: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, boolean, boolean] & {
        timestamp: bigint;
        isActive: boolean;
        scoreCalculated: boolean;
      }
    ],
    "view"
  >;

  getScoreWeights: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        incomeWeight: bigint;
        repaymentWeight: bigint;
        debtWeight: bigint;
        historyWeight: bigint;
      }
    ],
    "view"
  >;

  hasProfile: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isScoreFinalized: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestScoreDecryption: TypedContractMethod<[], [void], "nonpayable">;

  scoreDecryptionCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  updateProfile: TypedContractMethod<
    [
      encryptedIncome: BytesLike,
      incomeProof: BytesLike,
      encryptedRepaymentRate: BytesLike,
      repaymentProof: BytesLike,
      encryptedDebtRatio: BytesLike,
      debtProof: BytesLike,
      encryptedCreditHistory: BytesLike,
      historyProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeProfileCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateScore"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createProfile"
  ): TypedContractMethod<
    [
      encryptedIncome: BytesLike,
      incomeProof: BytesLike,
      encryptedRepaymentRate: BytesLike,
      repaymentProof: BytesLike,
      encryptedDebtRatio: BytesLike,
      debtProof: BytesLike,
      encryptedCreditHistory: BytesLike,
      historyProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creditProfiles"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        string,
        boolean,
        boolean
      ] & {
        encryptedIncome: string;
        encryptedRepaymentRate: string;
        encryptedDebtRatio: string;
        encryptedCreditHistory: string;
        encryptedScore: string;
        timestamp: bigint;
        owner: string;
        isActive: boolean;
        scoreCalculated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deleteProfile"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveProfileCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDecryptedScore"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedScore"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, boolean, boolean] & {
        timestamp: bigint;
        isActive: boolean;
        scoreCalculated: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScoreWeights"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        incomeWeight: bigint;
        repaymentWeight: bigint;
        debtWeight: bigint;
        historyWeight: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasProfile"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isScoreFinalized"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestScoreDecryption"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scoreDecryptionCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<
    [
      encryptedIncome: BytesLike,
      incomeProof: BytesLike,
      encryptedRepaymentRate: BytesLike,
      repaymentProof: BytesLike,
      encryptedDebtRatio: BytesLike,
      debtProof: BytesLike,
      encryptedCreditHistory: BytesLike,
      historyProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileDeleted"
  ): TypedContractEvent<
    ProfileDeletedEvent.InputTuple,
    ProfileDeletedEvent.OutputTuple,
    ProfileDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreCalculated"
  ): TypedContractEvent<
    ScoreCalculatedEvent.InputTuple,
    ScoreCalculatedEvent.OutputTuple,
    ScoreCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreDecryptionRequested"
  ): TypedContractEvent<
    ScoreDecryptionRequestedEvent.InputTuple,
    ScoreDecryptionRequestedEvent.OutputTuple,
    ScoreDecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreRevealed"
  ): TypedContractEvent<
    ScoreRevealedEvent.InputTuple,
    ScoreRevealedEvent.OutputTuple,
    ScoreRevealedEvent.OutputObject
  >;

  filters: {
    "ProfileCreated(address,uint256)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;

    "ProfileDeleted(address)": TypedContractEvent<
      ProfileDeletedEvent.InputTuple,
      ProfileDeletedEvent.OutputTuple,
      ProfileDeletedEvent.OutputObject
    >;
    ProfileDeleted: TypedContractEvent<
      ProfileDeletedEvent.InputTuple,
      ProfileDeletedEvent.OutputTuple,
      ProfileDeletedEvent.OutputObject
    >;

    "ProfileUpdated(address,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "ScoreCalculated(address,uint256)": TypedContractEvent<
      ScoreCalculatedEvent.InputTuple,
      ScoreCalculatedEvent.OutputTuple,
      ScoreCalculatedEvent.OutputObject
    >;
    ScoreCalculated: TypedContractEvent<
      ScoreCalculatedEvent.InputTuple,
      ScoreCalculatedEvent.OutputTuple,
      ScoreCalculatedEvent.OutputObject
    >;

    "ScoreDecryptionRequested(address,uint256)": TypedContractEvent<
      ScoreDecryptionRequestedEvent.InputTuple,
      ScoreDecryptionRequestedEvent.OutputTuple,
      ScoreDecryptionRequestedEvent.OutputObject
    >;
    ScoreDecryptionRequested: TypedContractEvent<
      ScoreDecryptionRequestedEvent.InputTuple,
      ScoreDecryptionRequestedEvent.OutputTuple,
      ScoreDecryptionRequestedEvent.OutputObject
    >;

    "ScoreRevealed(address,uint32)": TypedContractEvent<
      ScoreRevealedEvent.InputTuple,
      ScoreRevealedEvent.OutputTuple,
      ScoreRevealedEvent.OutputObject
    >;
    ScoreRevealed: TypedContractEvent<
      ScoreRevealedEvent.InputTuple,
      ScoreRevealedEvent.OutputTuple,
      ScoreRevealedEvent.OutputObject
    >;
  };
}
