/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SalaryVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deleteSalary"
      | "entryCount"
      | "getActiveEntryCount"
      | "getEncryptedPositionStats"
      | "getEncryptedSalary"
      | "getEncryptedStats"
      | "getEntry"
      | "getEntryCount"
      | "getGlobalStats"
      | "getPositionStats"
      | "globalStatsCallback"
      | "hasSubmitted"
      | "isPositionStatsFinalized"
      | "isStatsFinalized"
      | "positionStatsCallback"
      | "protocolId"
      | "requestGlobalStats"
      | "requestPositionStats"
      | "salaryEntries"
      | "submitSalary"
      | "updateSalary"
      | "userEntryId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PositionStatsPublished"
      | "PositionStatsRequested"
      | "SalaryDeleted"
      | "SalarySubmitted"
      | "SalaryUpdated"
      | "StatsPublished"
      | "StatsRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deleteSalary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedPositionStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedSalary",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "globalStatsCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPositionStatsFinalized",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isStatsFinalized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "positionStatsCallback",
    values: [BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestGlobalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestPositionStats",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "salaryEntries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitSalary",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSalary",
    values: [BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "userEntryId",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deleteSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "entryCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedPositionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEntryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "globalStatsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPositionStatsFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isStatsFinalized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "positionStatsCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestGlobalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestPositionStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salaryEntries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSalary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userEntryId",
    data: BytesLike
  ): Result;
}

export namespace PositionStatsPublishedEvent {
  export type InputTuple = [
    positionHash: BytesLike,
    averageSalary: BigNumberish,
    count: BigNumberish
  ];
  export type OutputTuple = [
    positionHash: string,
    averageSalary: bigint,
    count: bigint
  ];
  export interface OutputObject {
    positionHash: string;
    averageSalary: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionStatsRequestedEvent {
  export type InputTuple = [positionHash: BytesLike, requestId: BigNumberish];
  export type OutputTuple = [positionHash: string, requestId: bigint];
  export interface OutputObject {
    positionHash: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryDeletedEvent {
  export type InputTuple = [entryId: BigNumberish, submitter: AddressLike];
  export type OutputTuple = [entryId: bigint, submitter: string];
  export interface OutputObject {
    entryId: bigint;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalarySubmittedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    submitter: AddressLike,
    position: string
  ];
  export type OutputTuple = [
    entryId: bigint,
    submitter: string,
    position: string
  ];
  export interface OutputObject {
    entryId: bigint;
    submitter: string;
    position: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryUpdatedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    submitter: AddressLike,
    newPosition: string
  ];
  export type OutputTuple = [
    entryId: bigint,
    submitter: string,
    newPosition: string
  ];
  export interface OutputObject {
    entryId: bigint;
    submitter: string;
    newPosition: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatsPublishedEvent {
  export type InputTuple = [
    averageSalary: BigNumberish,
    totalCount: BigNumberish
  ];
  export type OutputTuple = [averageSalary: bigint, totalCount: bigint];
  export interface OutputObject {
    averageSalary: bigint;
    totalCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatsRequestedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SalaryVault extends BaseContract {
  connect(runner?: ContractRunner | null): SalaryVault;
  waitForDeployment(): Promise<this>;

  interface: SalaryVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteSalary: TypedContractMethod<[], [void], "nonpayable">;

  entryCount: TypedContractMethod<[], [bigint], "view">;

  getActiveEntryCount: TypedContractMethod<[], [bigint], "view">;

  getEncryptedPositionStats: TypedContractMethod<
    [position: string],
    [[string, bigint] & { encryptedTotal: string; count: bigint }],
    "view"
  >;

  getEncryptedSalary: TypedContractMethod<
    [entryId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedStats: TypedContractMethod<
    [],
    [[string, bigint] & { encryptedTotal: string; activeCount: bigint }],
    "view"
  >;

  getEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        position: string;
        timestamp: bigint;
        submitter: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEntryCount: TypedContractMethod<[], [bigint], "view">;

  getGlobalStats: TypedContractMethod<
    [],
    [[bigint, bigint] & { averageSalary: bigint; totalCount: bigint }],
    "view"
  >;

  getPositionStats: TypedContractMethod<
    [position: string],
    [[bigint, bigint] & { averageSalary: bigint; count: bigint }],
    "view"
  >;

  globalStatsCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  hasSubmitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isPositionStatsFinalized: TypedContractMethod<
    [position: string],
    [boolean],
    "view"
  >;

  isStatsFinalized: TypedContractMethod<[], [boolean], "view">;

  positionStatsCallback: TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestGlobalStats: TypedContractMethod<[], [void], "nonpayable">;

  requestPositionStats: TypedContractMethod<
    [position: string],
    [void],
    "nonpayable"
  >;

  salaryEntries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        submitter: string;
        position: string;
        encryptedSalary: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  submitSalary: TypedContractMethod<
    [encryptedSalary: BytesLike, inputProof: BytesLike, position: string],
    [void],
    "nonpayable"
  >;

  updateSalary: TypedContractMethod<
    [encryptedSalary: BytesLike, inputProof: BytesLike, newPosition: string],
    [void],
    "nonpayable"
  >;

  userEntryId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteSalary"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "entryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedPositionStats"
  ): TypedContractMethod<
    [position: string],
    [[string, bigint] & { encryptedTotal: string; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedSalary"
  ): TypedContractMethod<[entryId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedStats"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { encryptedTotal: string; activeCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [
      [string, bigint, string, boolean] & {
        position: string;
        timestamp: bigint;
        submitter: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGlobalStats"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { averageSalary: bigint; totalCount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPositionStats"
  ): TypedContractMethod<
    [position: string],
    [[bigint, bigint] & { averageSalary: bigint; count: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "globalStatsCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPositionStatsFinalized"
  ): TypedContractMethod<[position: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStatsFinalized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "positionStatsCallback"
  ): TypedContractMethod<
    [requestId: BigNumberish, cleartexts: BytesLike, arg2: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestGlobalStats"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestPositionStats"
  ): TypedContractMethod<[position: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "salaryEntries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        submitter: string;
        position: string;
        encryptedSalary: string;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitSalary"
  ): TypedContractMethod<
    [encryptedSalary: BytesLike, inputProof: BytesLike, position: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSalary"
  ): TypedContractMethod<
    [encryptedSalary: BytesLike, inputProof: BytesLike, newPosition: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userEntryId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "PositionStatsPublished"
  ): TypedContractEvent<
    PositionStatsPublishedEvent.InputTuple,
    PositionStatsPublishedEvent.OutputTuple,
    PositionStatsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "PositionStatsRequested"
  ): TypedContractEvent<
    PositionStatsRequestedEvent.InputTuple,
    PositionStatsRequestedEvent.OutputTuple,
    PositionStatsRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryDeleted"
  ): TypedContractEvent<
    SalaryDeletedEvent.InputTuple,
    SalaryDeletedEvent.OutputTuple,
    SalaryDeletedEvent.OutputObject
  >;
  getEvent(
    key: "SalarySubmitted"
  ): TypedContractEvent<
    SalarySubmittedEvent.InputTuple,
    SalarySubmittedEvent.OutputTuple,
    SalarySubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryUpdated"
  ): TypedContractEvent<
    SalaryUpdatedEvent.InputTuple,
    SalaryUpdatedEvent.OutputTuple,
    SalaryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StatsPublished"
  ): TypedContractEvent<
    StatsPublishedEvent.InputTuple,
    StatsPublishedEvent.OutputTuple,
    StatsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "StatsRequested"
  ): TypedContractEvent<
    StatsRequestedEvent.InputTuple,
    StatsRequestedEvent.OutputTuple,
    StatsRequestedEvent.OutputObject
  >;

  filters: {
    "PositionStatsPublished(bytes32,uint32,uint32)": TypedContractEvent<
      PositionStatsPublishedEvent.InputTuple,
      PositionStatsPublishedEvent.OutputTuple,
      PositionStatsPublishedEvent.OutputObject
    >;
    PositionStatsPublished: TypedContractEvent<
      PositionStatsPublishedEvent.InputTuple,
      PositionStatsPublishedEvent.OutputTuple,
      PositionStatsPublishedEvent.OutputObject
    >;

    "PositionStatsRequested(bytes32,uint256)": TypedContractEvent<
      PositionStatsRequestedEvent.InputTuple,
      PositionStatsRequestedEvent.OutputTuple,
      PositionStatsRequestedEvent.OutputObject
    >;
    PositionStatsRequested: TypedContractEvent<
      PositionStatsRequestedEvent.InputTuple,
      PositionStatsRequestedEvent.OutputTuple,
      PositionStatsRequestedEvent.OutputObject
    >;

    "SalaryDeleted(uint256,address)": TypedContractEvent<
      SalaryDeletedEvent.InputTuple,
      SalaryDeletedEvent.OutputTuple,
      SalaryDeletedEvent.OutputObject
    >;
    SalaryDeleted: TypedContractEvent<
      SalaryDeletedEvent.InputTuple,
      SalaryDeletedEvent.OutputTuple,
      SalaryDeletedEvent.OutputObject
    >;

    "SalarySubmitted(uint256,address,string)": TypedContractEvent<
      SalarySubmittedEvent.InputTuple,
      SalarySubmittedEvent.OutputTuple,
      SalarySubmittedEvent.OutputObject
    >;
    SalarySubmitted: TypedContractEvent<
      SalarySubmittedEvent.InputTuple,
      SalarySubmittedEvent.OutputTuple,
      SalarySubmittedEvent.OutputObject
    >;

    "SalaryUpdated(uint256,address,string)": TypedContractEvent<
      SalaryUpdatedEvent.InputTuple,
      SalaryUpdatedEvent.OutputTuple,
      SalaryUpdatedEvent.OutputObject
    >;
    SalaryUpdated: TypedContractEvent<
      SalaryUpdatedEvent.InputTuple,
      SalaryUpdatedEvent.OutputTuple,
      SalaryUpdatedEvent.OutputObject
    >;

    "StatsPublished(uint32,uint32)": TypedContractEvent<
      StatsPublishedEvent.InputTuple,
      StatsPublishedEvent.OutputTuple,
      StatsPublishedEvent.OutputObject
    >;
    StatsPublished: TypedContractEvent<
      StatsPublishedEvent.InputTuple,
      StatsPublishedEvent.OutputTuple,
      StatsPublishedEvent.OutputObject
    >;

    "StatsRequested(uint256)": TypedContractEvent<
      StatsRequestedEvent.InputTuple,
      StatsRequestedEvent.OutputTuple,
      StatsRequestedEvent.OutputObject
    >;
    StatsRequested: TypedContractEvent<
      StatsRequestedEvent.InputTuple,
      StatsRequestedEvent.OutputTuple,
      StatsRequestedEvent.OutputObject
    >;
  };
}
